#!/bin/sh
# (C) Frank Lübeckk 
export WWW2Dir=/home/wega/jneubues/WWW2
export SOURCE=gap@yin.dcs.st-and.ac.uk:/gap/PackageAdmin/webftp/Packages

cd $WWW2Dir/Manuals

echo "Dry run:"
rsync -av -c -n -e 'ssh -x -i /home/wega/jneubues/.ssh/gap_yin_rsa' $SOURCE/pkg .
echo "Shall I copy? (y/n)"
read ANSWER
echo

if [ $ANSWER = "y" ]; then
  echo "Ok, I'll copy ..."
  rsync -av -c -e 'ssh -x -i /home/wega/jneubues/.ssh/gap_yin_rsa' $SOURCE/pkg .
else
  echo "Don't copy, bye."
fi
