#!/bin/sh
# GETMR "name" "title"
# gets the MR-getitem link(s) for the specified paper.
# A.Hulpke, 8/23/01
echo $1 >DATFILE
NAM=`sed '1,$s/ /+/g' DATFILE`
echo $2 >DATFILE
SUB=`sed '1,$s/ /+/g' DATFILE`
echo $1 $2
lynx -dump "http://www.ams.org/mrlookup?s3=$NAM&pg3=ICN&s4=$SUB&pg4=TI&s5=&pg5=JOUR&ipage=&fpage=&arg3=&Search=Search&format=mrcit" >DATFILE
fgrep -- "-getitem" DATFILE|fgrep -v "e.g: <a href="
rm DATFILE
