#!/bin/sh
# MRBIB "MR-number"
# gets a bibtex entry for the item with the given MR (or CMP) number
# (requires MathSciNet access to work)
# example: MRBIB "91m:20026"
# A.Hulpke, 8/23/01
#lynx -dump "http://www.ams.org/mathscinet-getitem?mr=$1&return_type=bibtex" >DATFILE2
lynx -dump "http://www.ams.org/mathscinet/search/publications.html?fmt=bibtex&pg1=MR&s1="$1 > DATFILE2
awk 'BEGIN{flag=0;}\
{if (substr($0,1,1)=="@") {flag=1;}\
if (flag ==1) {print $0;}\
if (substr($0,1,1)=="}") {flag=0;}\
}' DATFILE2 |fgrep -v "ISSN"|fgrep -v "MRREVIEWER"|fgrep -v "CODEN"
echo
sleep 2
#rm DATFILE2
