name: "Sync"

on:
  workflow_dispatch:
  schedule:
    # Every day at 3:15 AM UTC
    - cron: '15 3 * * *'

jobs:
  sync:
    name: "Get new GitHub release data"
    if: ${{ github.repository == 'gap-system/GapWWW' }}
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the GapWWW repository in order to make changes to it"
        uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: 3.9
      - name: "Install the required Python modules"
        run: pip3 install PyGithub requests python-dateutil
      - name: "Run the GAP dev release script for updating the website"
        run: python -u etc/update_website.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Make a pull request to the master branch of this repository"
        uses: peter-evans/create-pull-request@v7
        with:
          base: master
          branch: auto/sync-with-github-releases
          commit-message: Sync data from GAP's GitHub release system
          title: Sync data from GAP's GitHub release system
          body: >-
            Automatically created by a GitHub Actions workflow, using with the
            GAP release script `dev/releases/update_website.py`.

            You may wish to squash and merge this pull request, in order
            to give it a more descriptive commit message.
